Repository wecode-bootcamp-korea/18-2nd-AirDropTheBeat-frontend, pull requests merged in 2021-04, with the labels that each got.

#6 Update README.md
  README.md
Labels: Status: Accepted

#4 [18기 권유진] Add: 숙소 상세 페이지 레이아웃 및 기능 구현 중
  package-lock.json
  package.json
  public/Data/main.json
  public/Images/defaultprofile.png
  public/Images/homeicon.png
  public/data/Back.json
  public/data/DetailMockData.json
  public/data/ReviewMockData.json
  src/Pages/Detail/.DetailMain.js.swo
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailAside.js
  src/Pages/Detail/DetailContents.js
  src/Pages/Detail/DetailImg.js
  src/Pages/Detail/DetailMain.js
  src/Pages/Detail/DetailMap.js
  src/Pages/Detail/DetailMap.scss
  src/Pages/Detail/DetailReview.js
  src/Pages/Detail/DetailSaveModal.js
  src/Pages/Detail/DetailTitle.js
  src/Routes.js
Labels: Status: 추가 기능 구현중

#2 [18기 윤찬호] Add : 메인, 리스트, 상세 페이지 붙여봄 디비 통신 완료
  .gitignore
  package-lock.json
  package.json
  public/Data/LatAndLng.json
  public/Data/listsHeader.json
  public/Data/listsRoom.json
  public/images/airdroptestimg.png
  public/images/defaultprofile.png
  public/images/homeicon.png
  public/index.html
  src/Components/Lists/Pagination.js
  src/Components/Lists/RoomList.js
  src/Components/Lists/RoomListContentBox.js
  src/Components/Lists/RoomListFooterBox.js
  src/Components/Lists/RoomListHeaderBox.js
  src/Components/Lists/RoomLists.js
  src/Components/Lists/RoomOption.js
  src/Components/Lists/RoomsHeader.js
  src/Components/Lists/RoomsMapAPI.js
  src/Components/Lists/RoomsSliderStyle.js
  src/Components/Nav/Nav.js
  src/Components/Nav/SelectOption.js
  src/Pages/Detail/DetailAside.js
  src/Pages/Detail/DetailContents.js
  src/Pages/Detail/DetailImg.js
  src/Pages/Detail/DetailMain.js
  src/Pages/Detail/DetailMap.js
  src/Pages/Detail/DetailReview.js
  src/Pages/Detail/DetailTitle.js
  src/Pages/Lists/Lists.js
  src/Pages/Lists/Lists.scss
  src/Pages/Lists/LocationInfoData.js
  src/Pages/Lists/Rooms/Rooms.js
  src/Pages/Lists/RoomsMap/RoomsMap.js
  src/Routes.js
  src/Styles/common.scss
  src/store/HeaderStore.js
  src/store/ListStore.js
Labels: Status: 리뷰 요청
